-- local lspconfig = require("lspconfig")
--
-- lspconfig.volar.setup({
--   filetypes = { "typescript", "javascript", "javascriptreact", "typescriptreact", "vue" },
--   init_options = {
--     typescript = {
--       tsdk = vim.fn.getcwd() .. "/node_modules/typescript/lib",
--     },
--     vue = {
--       hybridMode = false,
--     },
--   },
-- })
